#!/usr/bin/env bash
docker-compose up -d && \
echo "
==========================================================
Web server started: http://localhost:8000 🚀
==========================================================
"
